/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as EventsRouteImport } from './routes/events'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutBoardOfTrusteesRouteImport } from './routes/about.board-of-trustees'
import { Route as AboutCsrRouteImport } from './routes/about.csr'
import { Route as AboutProjectsRouteImport } from './routes/about.projects'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCloudHostingRouteImport } from './routes/services.cloud-hosting'
import { Route as ServicesTrustAndIdentityRouteImport } from './routes/services.trust-and-identity'
import { Route as ServicesInstitutionalRepositoriesIndexRouteImport } from './routes/services.institutional-repositories.index'
import { Route as ServicesInstitutionalRepositoriesDspaceRouteImport } from './routes/services.institutional-repositories.dspace'
import { Route as ServicesInstitutionalRepositoriesRumbuRouteImport } from './routes/services.institutional-repositories.rumbu'
import { Route as ServicesPersistentIdentifiersIndexRouteImport } from './routes/services.persistent-identifiers.index'
import { Route as ServicesPersistentIdentifiersDoisRouteImport } from './routes/services.persistent-identifiers.dois'
import { Route as ServicesPersistentIdentifiersOrcidConsortiumRouteImport } from './routes/services.persistent-identifiers.orcid-consortium'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardOfTrusteesRoute = AboutBoardOfTrusteesRouteImport.update({
  id: '/about/board-of-trustees',
  path: '/about/board-of-trustees',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCsrRoute = AboutCsrRouteImport.update({
  id: '/about/csr',
  path: '/about/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutProjectsRoute = AboutProjectsRouteImport.update({
  id: '/about/projects',
  path: '/about/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudHostingRoute = ServicesCloudHostingRouteImport.update({
  id: '/services/cloud-hosting',
  path: '/services/cloud-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrustAndIdentityRoute =
  ServicesTrustAndIdentityRouteImport.update({
    id: '/services/trust-and-identity',
    path: '/services/trust-and-identity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstitutionalRepositoriesIndexRoute =
  ServicesInstitutionalRepositoriesIndexRouteImport.update({
    id: '/services/institutional-repositories/',
    path: '/services/institutional-repositories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstitutionalRepositoriesDspaceRoute =
  ServicesInstitutionalRepositoriesDspaceRouteImport.update({
    id: '/services/institutional-repositories/dspace',
    path: '/services/institutional-repositories/dspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstitutionalRepositoriesRumbuRoute =
  ServicesInstitutionalRepositoriesRumbuRouteImport.update({
    id: '/services/institutional-repositories/rumbu',
    path: '/services/institutional-repositories/rumbu',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersistentIdentifiersIndexRoute =
  ServicesPersistentIdentifiersIndexRouteImport.update({
    id: '/services/persistent-identifiers/',
    path: '/services/persistent-identifiers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersistentIdentifiersDoisRoute =
  ServicesPersistentIdentifiersDoisRouteImport.update({
    id: '/services/persistent-identifiers/dois',
    path: '/services/persistent-identifiers/dois',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersistentIdentifiersOrcidConsortiumRoute =
  ServicesPersistentIdentifiersOrcidConsortiumRouteImport.update({
    id: '/services/persistent-identifiers/orcid-consortium',
    path: '/services/persistent-identifiers/orcid-consortium',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/board-of-trustees': typeof AboutBoardOfTrusteesRoute
  '/about/csr': typeof AboutCsrRoute
  '/about/projects': typeof AboutProjectsRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/trust-and-identity': typeof ServicesTrustAndIdentityRoute
  '/about/': typeof AboutIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/institutional-repositories/dspace': typeof ServicesInstitutionalRepositoriesDspaceRoute
  '/services/institutional-repositories/rumbu': typeof ServicesInstitutionalRepositoriesRumbuRoute
  '/services/persistent-identifiers/dois': typeof ServicesPersistentIdentifiersDoisRoute
  '/services/persistent-identifiers/orcid-consortium': typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  '/services/institutional-repositories/': typeof ServicesInstitutionalRepositoriesIndexRoute
  '/services/persistent-identifiers/': typeof ServicesPersistentIdentifiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/board-of-trustees': typeof AboutBoardOfTrusteesRoute
  '/about/csr': typeof AboutCsrRoute
  '/about/projects': typeof AboutProjectsRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/trust-and-identity': typeof ServicesTrustAndIdentityRoute
  '/about': typeof AboutIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/institutional-repositories/dspace': typeof ServicesInstitutionalRepositoriesDspaceRoute
  '/services/institutional-repositories/rumbu': typeof ServicesInstitutionalRepositoriesRumbuRoute
  '/services/persistent-identifiers/dois': typeof ServicesPersistentIdentifiersDoisRoute
  '/services/persistent-identifiers/orcid-consortium': typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  '/services/institutional-repositories': typeof ServicesInstitutionalRepositoriesIndexRoute
  '/services/persistent-identifiers': typeof ServicesPersistentIdentifiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/board-of-trustees': typeof AboutBoardOfTrusteesRoute
  '/about/csr': typeof AboutCsrRoute
  '/about/projects': typeof AboutProjectsRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/trust-and-identity': typeof ServicesTrustAndIdentityRoute
  '/about/': typeof AboutIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/institutional-repositories/dspace': typeof ServicesInstitutionalRepositoriesDspaceRoute
  '/services/institutional-repositories/rumbu': typeof ServicesInstitutionalRepositoriesRumbuRoute
  '/services/persistent-identifiers/dois': typeof ServicesPersistentIdentifiersDoisRoute
  '/services/persistent-identifiers/orcid-consortium': typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  '/services/institutional-repositories/': typeof ServicesInstitutionalRepositoriesIndexRoute
  '/services/persistent-identifiers/': typeof ServicesPersistentIdentifiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/about/board-of-trustees'
    | '/about/csr'
    | '/about/projects'
    | '/services/cloud-hosting'
    | '/services/trust-and-identity'
    | '/about/'
    | '/services/'
    | '/services/institutional-repositories/dspace'
    | '/services/institutional-repositories/rumbu'
    | '/services/persistent-identifiers/dois'
    | '/services/persistent-identifiers/orcid-consortium'
    | '/services/institutional-repositories/'
    | '/services/persistent-identifiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/about/board-of-trustees'
    | '/about/csr'
    | '/about/projects'
    | '/services/cloud-hosting'
    | '/services/trust-and-identity'
    | '/about'
    | '/services'
    | '/services/institutional-repositories/dspace'
    | '/services/institutional-repositories/rumbu'
    | '/services/persistent-identifiers/dois'
    | '/services/persistent-identifiers/orcid-consortium'
    | '/services/institutional-repositories'
    | '/services/persistent-identifiers'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/about/board-of-trustees'
    | '/about/csr'
    | '/about/projects'
    | '/services/cloud-hosting'
    | '/services/trust-and-identity'
    | '/about/'
    | '/services/'
    | '/services/institutional-repositories/dspace'
    | '/services/institutional-repositories/rumbu'
    | '/services/persistent-identifiers/dois'
    | '/services/persistent-identifiers/orcid-consortium'
    | '/services/institutional-repositories/'
    | '/services/persistent-identifiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AboutBoardOfTrusteesRoute: typeof AboutBoardOfTrusteesRoute
  AboutCsrRoute: typeof AboutCsrRoute
  AboutProjectsRoute: typeof AboutProjectsRoute
  ServicesCloudHostingRoute: typeof ServicesCloudHostingRoute
  ServicesTrustAndIdentityRoute: typeof ServicesTrustAndIdentityRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesInstitutionalRepositoriesDspaceRoute: typeof ServicesInstitutionalRepositoriesDspaceRoute
  ServicesInstitutionalRepositoriesRumbuRoute: typeof ServicesInstitutionalRepositoriesRumbuRoute
  ServicesPersistentIdentifiersDoisRoute: typeof ServicesPersistentIdentifiersDoisRoute
  ServicesPersistentIdentifiersOrcidConsortiumRoute: typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  ServicesInstitutionalRepositoriesIndexRoute: typeof ServicesInstitutionalRepositoriesIndexRoute
  ServicesPersistentIdentifiersIndexRoute: typeof ServicesPersistentIdentifiersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board-of-trustees': {
      id: '/about/board-of-trustees'
      path: '/about/board-of-trustees'
      fullPath: '/about/board-of-trustees'
      preLoaderRoute: typeof AboutBoardOfTrusteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/csr': {
      id: '/about/csr'
      path: '/about/csr'
      fullPath: '/about/csr'
      preLoaderRoute: typeof AboutCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/projects': {
      id: '/about/projects'
      path: '/about/projects'
      fullPath: '/about/projects'
      preLoaderRoute: typeof AboutProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-hosting': {
      id: '/services/cloud-hosting'
      path: '/services/cloud-hosting'
      fullPath: '/services/cloud-hosting'
      preLoaderRoute: typeof ServicesCloudHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/trust-and-identity': {
      id: '/services/trust-and-identity'
      path: '/services/trust-and-identity'
      fullPath: '/services/trust-and-identity'
      preLoaderRoute: typeof ServicesTrustAndIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/institutional-repositories/': {
      id: '/services/institutional-repositories/'
      path: '/services/institutional-repositories'
      fullPath: '/services/institutional-repositories/'
      preLoaderRoute: typeof ServicesInstitutionalRepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/institutional-repositories/dspace': {
      id: '/services/institutional-repositories/dspace'
      path: '/services/institutional-repositories/dspace'
      fullPath: '/services/institutional-repositories/dspace'
      preLoaderRoute: typeof ServicesInstitutionalRepositoriesDspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/institutional-repositories/rumbu': {
      id: '/services/institutional-repositories/rumbu'
      path: '/services/institutional-repositories/rumbu'
      fullPath: '/services/institutional-repositories/rumbu'
      preLoaderRoute: typeof ServicesInstitutionalRepositoriesRumbuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/persistent-identifiers/': {
      id: '/services/persistent-identifiers/'
      path: '/services/persistent-identifiers'
      fullPath: '/services/persistent-identifiers/'
      preLoaderRoute: typeof ServicesPersistentIdentifiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/persistent-identifiers/dois': {
      id: '/services/persistent-identifiers/dois'
      path: '/services/persistent-identifiers/dois'
      fullPath: '/services/persistent-identifiers/dois'
      preLoaderRoute: typeof ServicesPersistentIdentifiersDoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/persistent-identifiers/orcid-consortium': {
      id: '/services/persistent-identifiers/orcid-consortium'
      path: '/services/persistent-identifiers/orcid-consortium'
      fullPath: '/services/persistent-identifiers/orcid-consortium'
      preLoaderRoute: typeof ServicesPersistentIdentifiersOrcidConsortiumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AboutBoardOfTrusteesRoute: AboutBoardOfTrusteesRoute,
  AboutCsrRoute: AboutCsrRoute,
  AboutProjectsRoute: AboutProjectsRoute,
  ServicesCloudHostingRoute: ServicesCloudHostingRoute,
  ServicesTrustAndIdentityRoute: ServicesTrustAndIdentityRoute,
  AboutIndexRoute: AboutIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesInstitutionalRepositoriesDspaceRoute:
    ServicesInstitutionalRepositoriesDspaceRoute,
  ServicesInstitutionalRepositoriesRumbuRoute:
    ServicesInstitutionalRepositoriesRumbuRoute,
  ServicesPersistentIdentifiersDoisRoute:
    ServicesPersistentIdentifiersDoisRoute,
  ServicesPersistentIdentifiersOrcidConsortiumRoute:
    ServicesPersistentIdentifiersOrcidConsortiumRoute,
  ServicesInstitutionalRepositoriesIndexRoute:
    ServicesInstitutionalRepositoriesIndexRoute,
  ServicesPersistentIdentifiersIndexRoute:
    ServicesPersistentIdentifiersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
