/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutBoardOfTrusteesRouteImport } from './routes/about.board-of-trustees'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityRenNgRouteImport } from './routes/community.ren-ng'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsPastEventsRouteImport } from './routes/events.past-events'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaBlogRouteImport } from './routes/media.blog'
import { Route as MediaLinkedinRouteImport } from './routes/media.linkedin'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsCsrRouteImport } from './routes/projects.csr'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCloudHostingRouteImport } from './routes/services.cloud-hosting'
import { Route as ServicesTrustAndIdentityRouteImport } from './routes/services.trust-and-identity'
import { Route as ServicesInstitutionalRepositoriesIndexRouteImport } from './routes/services.institutional-repositories.index'
import { Route as ServicesInstitutionalRepositoriesDspaceRouteImport } from './routes/services.institutional-repositories.dspace'
import { Route as ServicesInstitutionalRepositoriesRumbuRouteImport } from './routes/services.institutional-repositories.rumbu'
import { Route as ServicesPersistentIdentifiersIndexRouteImport } from './routes/services.persistent-identifiers.index'
import { Route as ServicesPersistentIdentifiersDoisRouteImport } from './routes/services.persistent-identifiers.dois'
import { Route as ServicesPersistentIdentifiersOrcidConsortiumRouteImport } from './routes/services.persistent-identifiers.orcid-consortium'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardOfTrusteesRoute = AboutBoardOfTrusteesRouteImport.update({
  id: '/about/board-of-trustees',
  path: '/about/board-of-trustees',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRenNgRoute = CommunityRenNgRouteImport.update({
  id: '/community/ren-ng',
  path: '/community/ren-ng',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsPastEventsRoute = EventsPastEventsRouteImport.update({
  id: '/events/past-events',
  path: '/events/past-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaBlogRoute = MediaBlogRouteImport.update({
  id: '/media/blog',
  path: '/media/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLinkedinRoute = MediaLinkedinRouteImport.update({
  id: '/media/linkedin',
  path: '/media/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCsrRoute = ProjectsCsrRouteImport.update({
  id: '/projects/csr',
  path: '/projects/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudHostingRoute = ServicesCloudHostingRouteImport.update({
  id: '/services/cloud-hosting',
  path: '/services/cloud-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrustAndIdentityRoute =
  ServicesTrustAndIdentityRouteImport.update({
    id: '/services/trust-and-identity',
    path: '/services/trust-and-identity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstitutionalRepositoriesIndexRoute =
  ServicesInstitutionalRepositoriesIndexRouteImport.update({
    id: '/services/institutional-repositories/',
    path: '/services/institutional-repositories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstitutionalRepositoriesDspaceRoute =
  ServicesInstitutionalRepositoriesDspaceRouteImport.update({
    id: '/services/institutional-repositories/dspace',
    path: '/services/institutional-repositories/dspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstitutionalRepositoriesRumbuRoute =
  ServicesInstitutionalRepositoriesRumbuRouteImport.update({
    id: '/services/institutional-repositories/rumbu',
    path: '/services/institutional-repositories/rumbu',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersistentIdentifiersIndexRoute =
  ServicesPersistentIdentifiersIndexRouteImport.update({
    id: '/services/persistent-identifiers/',
    path: '/services/persistent-identifiers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersistentIdentifiersDoisRoute =
  ServicesPersistentIdentifiersDoisRouteImport.update({
    id: '/services/persistent-identifiers/dois',
    path: '/services/persistent-identifiers/dois',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPersistentIdentifiersOrcidConsortiumRoute =
  ServicesPersistentIdentifiersOrcidConsortiumRouteImport.update({
    id: '/services/persistent-identifiers/orcid-consortium',
    path: '/services/persistent-identifiers/orcid-consortium',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/board-of-trustees': typeof AboutBoardOfTrusteesRoute
  '/community/ren-ng': typeof CommunityRenNgRoute
  '/events/past-events': typeof EventsPastEventsRoute
  '/media/blog': typeof MediaBlogRoute
  '/media/linkedin': typeof MediaLinkedinRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/csr': typeof ProjectsCsrRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/trust-and-identity': typeof ServicesTrustAndIdentityRoute
  '/about/': typeof AboutIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/events/': typeof EventsIndexRoute
  '/media/': typeof MediaIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/institutional-repositories/dspace': typeof ServicesInstitutionalRepositoriesDspaceRoute
  '/services/institutional-repositories/rumbu': typeof ServicesInstitutionalRepositoriesRumbuRoute
  '/services/persistent-identifiers/dois': typeof ServicesPersistentIdentifiersDoisRoute
  '/services/persistent-identifiers/orcid-consortium': typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  '/services/institutional-repositories/': typeof ServicesInstitutionalRepositoriesIndexRoute
  '/services/persistent-identifiers/': typeof ServicesPersistentIdentifiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/board-of-trustees': typeof AboutBoardOfTrusteesRoute
  '/community/ren-ng': typeof CommunityRenNgRoute
  '/events/past-events': typeof EventsPastEventsRoute
  '/media/blog': typeof MediaBlogRoute
  '/media/linkedin': typeof MediaLinkedinRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/csr': typeof ProjectsCsrRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/trust-and-identity': typeof ServicesTrustAndIdentityRoute
  '/about': typeof AboutIndexRoute
  '/community': typeof CommunityIndexRoute
  '/events': typeof EventsIndexRoute
  '/media': typeof MediaIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/institutional-repositories/dspace': typeof ServicesInstitutionalRepositoriesDspaceRoute
  '/services/institutional-repositories/rumbu': typeof ServicesInstitutionalRepositoriesRumbuRoute
  '/services/persistent-identifiers/dois': typeof ServicesPersistentIdentifiersDoisRoute
  '/services/persistent-identifiers/orcid-consortium': typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  '/services/institutional-repositories': typeof ServicesInstitutionalRepositoriesIndexRoute
  '/services/persistent-identifiers': typeof ServicesPersistentIdentifiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/board-of-trustees': typeof AboutBoardOfTrusteesRoute
  '/community/ren-ng': typeof CommunityRenNgRoute
  '/events/past-events': typeof EventsPastEventsRoute
  '/media/blog': typeof MediaBlogRoute
  '/media/linkedin': typeof MediaLinkedinRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/csr': typeof ProjectsCsrRoute
  '/services/cloud-hosting': typeof ServicesCloudHostingRoute
  '/services/trust-and-identity': typeof ServicesTrustAndIdentityRoute
  '/about/': typeof AboutIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/events/': typeof EventsIndexRoute
  '/media/': typeof MediaIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/institutional-repositories/dspace': typeof ServicesInstitutionalRepositoriesDspaceRoute
  '/services/institutional-repositories/rumbu': typeof ServicesInstitutionalRepositoriesRumbuRoute
  '/services/persistent-identifiers/dois': typeof ServicesPersistentIdentifiersDoisRoute
  '/services/persistent-identifiers/orcid-consortium': typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  '/services/institutional-repositories/': typeof ServicesInstitutionalRepositoriesIndexRoute
  '/services/persistent-identifiers/': typeof ServicesPersistentIdentifiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news'
    | '/sitemap.xml'
    | '/about/board-of-trustees'
    | '/community/ren-ng'
    | '/events/past-events'
    | '/media/blog'
    | '/media/linkedin'
    | '/projects/$slug'
    | '/projects/csr'
    | '/services/cloud-hosting'
    | '/services/trust-and-identity'
    | '/about/'
    | '/community/'
    | '/events/'
    | '/media/'
    | '/projects/'
    | '/services/'
    | '/services/institutional-repositories/dspace'
    | '/services/institutional-repositories/rumbu'
    | '/services/persistent-identifiers/dois'
    | '/services/persistent-identifiers/orcid-consortium'
    | '/services/institutional-repositories/'
    | '/services/persistent-identifiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news'
    | '/sitemap.xml'
    | '/about/board-of-trustees'
    | '/community/ren-ng'
    | '/events/past-events'
    | '/media/blog'
    | '/media/linkedin'
    | '/projects/$slug'
    | '/projects/csr'
    | '/services/cloud-hosting'
    | '/services/trust-and-identity'
    | '/about'
    | '/community'
    | '/events'
    | '/media'
    | '/projects'
    | '/services'
    | '/services/institutional-repositories/dspace'
    | '/services/institutional-repositories/rumbu'
    | '/services/persistent-identifiers/dois'
    | '/services/persistent-identifiers/orcid-consortium'
    | '/services/institutional-repositories'
    | '/services/persistent-identifiers'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/sitemap.xml'
    | '/about/board-of-trustees'
    | '/community/ren-ng'
    | '/events/past-events'
    | '/media/blog'
    | '/media/linkedin'
    | '/projects/$slug'
    | '/projects/csr'
    | '/services/cloud-hosting'
    | '/services/trust-and-identity'
    | '/about/'
    | '/community/'
    | '/events/'
    | '/media/'
    | '/projects/'
    | '/services/'
    | '/services/institutional-repositories/dspace'
    | '/services/institutional-repositories/rumbu'
    | '/services/persistent-identifiers/dois'
    | '/services/persistent-identifiers/orcid-consortium'
    | '/services/institutional-repositories/'
    | '/services/persistent-identifiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AboutBoardOfTrusteesRoute: typeof AboutBoardOfTrusteesRoute
  CommunityRenNgRoute: typeof CommunityRenNgRoute
  EventsPastEventsRoute: typeof EventsPastEventsRoute
  MediaBlogRoute: typeof MediaBlogRoute
  MediaLinkedinRoute: typeof MediaLinkedinRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsCsrRoute: typeof ProjectsCsrRoute
  ServicesCloudHostingRoute: typeof ServicesCloudHostingRoute
  ServicesTrustAndIdentityRoute: typeof ServicesTrustAndIdentityRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesInstitutionalRepositoriesDspaceRoute: typeof ServicesInstitutionalRepositoriesDspaceRoute
  ServicesInstitutionalRepositoriesRumbuRoute: typeof ServicesInstitutionalRepositoriesRumbuRoute
  ServicesPersistentIdentifiersDoisRoute: typeof ServicesPersistentIdentifiersDoisRoute
  ServicesPersistentIdentifiersOrcidConsortiumRoute: typeof ServicesPersistentIdentifiersOrcidConsortiumRoute
  ServicesInstitutionalRepositoriesIndexRoute: typeof ServicesInstitutionalRepositoriesIndexRoute
  ServicesPersistentIdentifiersIndexRoute: typeof ServicesPersistentIdentifiersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board-of-trustees': {
      id: '/about/board-of-trustees'
      path: '/about/board-of-trustees'
      fullPath: '/about/board-of-trustees'
      preLoaderRoute: typeof AboutBoardOfTrusteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/ren-ng': {
      id: '/community/ren-ng'
      path: '/community/ren-ng'
      fullPath: '/community/ren-ng'
      preLoaderRoute: typeof CommunityRenNgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/past-events': {
      id: '/events/past-events'
      path: '/events/past-events'
      fullPath: '/events/past-events'
      preLoaderRoute: typeof EventsPastEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/blog': {
      id: '/media/blog'
      path: '/media/blog'
      fullPath: '/media/blog'
      preLoaderRoute: typeof MediaBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/linkedin': {
      id: '/media/linkedin'
      path: '/media/linkedin'
      fullPath: '/media/linkedin'
      preLoaderRoute: typeof MediaLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/csr': {
      id: '/projects/csr'
      path: '/projects/csr'
      fullPath: '/projects/csr'
      preLoaderRoute: typeof ProjectsCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-hosting': {
      id: '/services/cloud-hosting'
      path: '/services/cloud-hosting'
      fullPath: '/services/cloud-hosting'
      preLoaderRoute: typeof ServicesCloudHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/trust-and-identity': {
      id: '/services/trust-and-identity'
      path: '/services/trust-and-identity'
      fullPath: '/services/trust-and-identity'
      preLoaderRoute: typeof ServicesTrustAndIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/institutional-repositories/': {
      id: '/services/institutional-repositories/'
      path: '/services/institutional-repositories'
      fullPath: '/services/institutional-repositories/'
      preLoaderRoute: typeof ServicesInstitutionalRepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/institutional-repositories/dspace': {
      id: '/services/institutional-repositories/dspace'
      path: '/services/institutional-repositories/dspace'
      fullPath: '/services/institutional-repositories/dspace'
      preLoaderRoute: typeof ServicesInstitutionalRepositoriesDspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/institutional-repositories/rumbu': {
      id: '/services/institutional-repositories/rumbu'
      path: '/services/institutional-repositories/rumbu'
      fullPath: '/services/institutional-repositories/rumbu'
      preLoaderRoute: typeof ServicesInstitutionalRepositoriesRumbuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/persistent-identifiers/': {
      id: '/services/persistent-identifiers/'
      path: '/services/persistent-identifiers'
      fullPath: '/services/persistent-identifiers/'
      preLoaderRoute: typeof ServicesPersistentIdentifiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/persistent-identifiers/dois': {
      id: '/services/persistent-identifiers/dois'
      path: '/services/persistent-identifiers/dois'
      fullPath: '/services/persistent-identifiers/dois'
      preLoaderRoute: typeof ServicesPersistentIdentifiersDoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/persistent-identifiers/orcid-consortium': {
      id: '/services/persistent-identifiers/orcid-consortium'
      path: '/services/persistent-identifiers/orcid-consortium'
      fullPath: '/services/persistent-identifiers/orcid-consortium'
      preLoaderRoute: typeof ServicesPersistentIdentifiersOrcidConsortiumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AboutBoardOfTrusteesRoute: AboutBoardOfTrusteesRoute,
  CommunityRenNgRoute: CommunityRenNgRoute,
  EventsPastEventsRoute: EventsPastEventsRoute,
  MediaBlogRoute: MediaBlogRoute,
  MediaLinkedinRoute: MediaLinkedinRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsCsrRoute: ProjectsCsrRoute,
  ServicesCloudHostingRoute: ServicesCloudHostingRoute,
  ServicesTrustAndIdentityRoute: ServicesTrustAndIdentityRoute,
  AboutIndexRoute: AboutIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesInstitutionalRepositoriesDspaceRoute:
    ServicesInstitutionalRepositoriesDspaceRoute,
  ServicesInstitutionalRepositoriesRumbuRoute:
    ServicesInstitutionalRepositoriesRumbuRoute,
  ServicesPersistentIdentifiersDoisRoute:
    ServicesPersistentIdentifiersDoisRoute,
  ServicesPersistentIdentifiersOrcidConsortiumRoute:
    ServicesPersistentIdentifiersOrcidConsortiumRoute,
  ServicesInstitutionalRepositoriesIndexRoute:
    ServicesInstitutionalRepositoriesIndexRoute,
  ServicesPersistentIdentifiersIndexRoute:
    ServicesPersistentIdentifiersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
